### ISSUE TITLE
cooliris.swf is still looking for some files hosted on cooliris.com

### ISSUE THREAD

**Issue by librarymark** [cooliris/embed-wall#2]
Hello - I am hosting cooliris.swf on my website and it works fine, but the SWF is still looking for sharing2.png, c2_logo_white.png, and crossdomain.xml from apps.cooliris.com when it loads up. Is that anything to be concerned about? Should that still be happening still or am I doing something wrong? It would be nice to have that compiled out.

**Comment by mackermann2** [comment]
Hello,
I have the same problem. Logo of Facebook and Twitter is not displayed.
Is there a setting to define a new path or disable the display of these?
Thnanks in advance,
Matthieu

**Comment by ashoemaker** [comment]
Hi – that is expected, unfortunately we were unable to remove those URL dependencies when making the final version of the SWF available here. The cooliris.com domain is now managed by Yahoo, so those requests should 404 harmlessly.

**Comment by JimOL** [comment]
With all respect, it is not a good answer to say that Yahoo bought Cooliris and therefore you are not responsible for cooliris.swf. I have invested several years worth of web albums created with cooliris and now although I have downloaded cooliris.swf to my web host, none of the albums show up because coolliris.swf is looking for crossdomain.xml on your site. It should be easy for your developers who created this complex software to open it in Flash and change it so that cooliris.swf is looking for crossdowmain.xml on a relative path.

Thanks
